development:
  adapter: mysql2
  database: my_finances_development
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: my_finances_production
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: my_finances_test
  username: root
  password:
  host: localhost
  encoding: utf8
